### ISSUE TITLE
thrown in /chroot/home/mtwogall/m2.galleyline.com/html/app/code/Cadence/External/Model/Integration.php on line 171 #3 {main} #2 /chroot/home/mtwogall/m2.galleyline.com/html/pricereg1.php(59): Cadence\External\Framework\App\External->launch(Array) #1 /chroot/home/mtwogall/m2.galleyline.com/html/app/code/Cadence/External/Framework/App/External.php(145): Cadence\External\Model\Integration->configure(Array) #0 /chroot/home/mtwogall/m2.galleyline.com/html/app/code/Cadence/External/Model/Integration.php(65): Cadence\External\Model\Integration->initView() Stack trace: [20-Sep-2018 15:39:40 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Framework\View\Result\Page\Interceptor::getPageComponents() in /chroot/home/mtwogall/m2.galleyline.com/html/app/code/Cadence/External/Model/Integration.php:171

### ISSUE THREAD

**Issue by scottbolasevich** [cadencelabs/m2external#3]
just a basic script/copied code from tutorial.

baffled

**Comment by scottbolasevich** [comment]
this is because you need todo rm -rf generated/* and then it worked
